steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args: ['-c', 'gcloud app deploy app.yaml --project=$PROJECT_ID']

# Adaugă exact aceste două rânduri la final:
options:
  logging: CLOUD_LOGGING_ONLY
